--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: wordpress-pvc
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: wordpress-pvc-mysql
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
